config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :lessons
  devise_for :users
  resources :courses do
      get :purchased, :pending_review, :created, :unapproved, on: :collection
      member do
        patch :approve
        patch :unapprove
      end
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  root 'static_pages#landing_page'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'activity', to: 'static_pages#activity'
  resources :users, only: [:index, :edit, :show, :update]
  get 'analytics', to: 'static_pages#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest
    @top_rated = Course.top_rated
    @popular = Course.popular
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin)
      @activities = PublicActivity::Activity.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def analytics
    if current_user.has_role?(:admin)
      @users = User.all
      @enrollments = Enrollment.all
      @courses = Course.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/activity.html.erb
<% content_for :title do %>
  Corsego
  \|
  Activity
<% end %>


<h3>
  <div class="text-center">
    Activity
    <div class="badge badge-info">
      <%= @activities.count %>
    </div>
  </div>
</h3>
<p></p>
<ul class="list-group">
  <% @activities.each do |activity| %>
    <li class="list-group-item">
      <%= activity.id %>
      <%= activity.trackable_type %>
      <%= activity.trackable_id %>
      <%= link_to activity.trackable, activity.trackable %>
      <%= activity.key %>
      <%= activity.parameters %>
      <%= activity.owner %>
    </li>
  <% end %>
</ul>

app/views/static_pages/analytics.html.erb
<h4 class="text-center">
  New users per day
</h4>
<!--= line_chart @users.group_by_day(:created_at).count
-->
<%= line_chart charts_users_per_day_path %>
<h4 class="text-center">
  New enrollments per day
</h4>
<!--= column_chart @enrollments.group_by_day(:created_at).count
-->
<%= column_chart charts_enrollments_per_day_path %>
<h4 class="text-center">
  Most enrolled courses
</h4>
<!--= pie_chart @courses.group(:enrollments_count).count
-->
<!--= pie_chart @enrollments.joins(:course).group(:'courses.title').count
-->
<!--= bar_chart @enrollments.joins(:course).group(:'courses.title').count
-->
<%= bar_chart charts_course_popularity_path %>
<h4 class="text-center">
  Most paid courses
</h4>
<%= bar_chart charts_money_makers_path %>

app/views/static_pages/landing_page.html.erb
<% content_for :title do %>
  Corsego
  \|
  Online Courses - Learn Anything, On Your Schedule
<% end %>
<div class="jumbotron">
  <div class="display-4">
    What do you want to learn today?
  </div>
  <div class="p-4"></div>
  <% if current_user %>
    <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
      <div class="input-group">
        <%= f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off %>
        <span class="input-group-append">
          <button class="btn btn-primary btn-sm" type="submit">
            <span aria-hidden="true" class="fa fa-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  <% end %>

</div>
<div class="card-group">
  <div class="card card-body">
    <h1>
      <div class="fa fa-graduation-cap"></div>
    </h1>
    <%= Course.count %>
    online courses
    <div class="row"></div>
    Explore a variety of fresh topics
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-chalkboard-teacher"></div>
      <!--.fa.fa-brain
      -->
    </h1>
    <%= Course.distinct.count(:user_id) %>
    expert instructors
    <div class="row"></div>
    Find the right instructor for you
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-user-graduate"></div>
    </h1>
    <%= User.count %>
    active learners
    <div class="row"></div>
    Join the knowledge sharing community
  </div>
  <div class="card card-body">
    <h1>
      <div class="fa fa-infinity"></div>
    </h1>
    Lifetime access
    <div class="row"></div>
    Learn on your schedule
  </div>
</div>

<p></p>

<h2>
  <div class="fa fa-user-graduate"></div>
  Continue Learning
</h2>
<div class="card-columns d-flex justify-content-around">
  <% @purchased_courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>
<h2>
  <div class="fa fa-chart-line"></div>
  Popular courses
</h2>
  <div class="card-columns d-flex justify-content-around">
    <% @popular.each do |course| %>
      <%= render 'courses/course', course: course %>
    <% end %>
  </div>
<hr/>
<h2>
  <div class="fa fa-star"></div>
  Top rated courses
</h2>
<div class="card-columns d-flex justify-content-around">
  <% @top_rated.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>
<h2>
  <div class="fa fa-clock"></div>
  Latest courses
</h2>
<div class="card-columns d-flex justify-content-around">
  <% @latest.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr/>
<h2>
  <div class="fa fa-comment"></div>
  What our students have to say
</h2>
<div class="card-columns">
  <% @latest_good_reviews.each do |enrollment| %>
    <%= render 'enrollments/enrollment', enrollment: enrollment %>
  <% end %>
</div>

app/views/static_pages/privacy_policy.html.erb
<h1>Hello world</h1>

<%= link_to "Landing Page", root_path, class: "btn btn-primary text-white"  %>
<div class="jumbotron">
  <div class="display-4">
    What do you want to learn today?
  </div>
  <div class="p-4"></div>
</div>