config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :lessons
  devise_for :users
  resources :courses do
      get :purchased, :pending_review, :created, :unapproved, on: :collection
      member do
        patch :approve
        patch :unapprove
      end
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  root 'static_pages#landing_page'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'activity', to: 'static_pages#activity'
  resources :users, only: [:index, :edit, :show, :update]
  get 'analytics', to: 'static_pages#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  validates :title, :content, :course, presence: true
  # Course.find_each { |course| Course.reset_counters(course.id, :lessons) }
  has_rich_text :content
  has_many :user_lessons, dependent: :destroy


  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  def to_s
    title
  end

  def viewed(user)
    self.user_lessons.where(user: user).present?
  end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons
  end

  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  def edit
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :content)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<% # frozen_string_literal: true %>
<%= simple_form_for([@course, @lesson]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
    <%= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden %>
    <small>
      <%= f.error :content, class: 'text-danger' %>
    </small>

  </div>
  <p></p>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div class="card">
  <div class="card-header">
    <% if lesson.viewed(current_user) == true %>
      <div class="text-success far fa-check-square"></div>
      <!--VIEWED
      -->
    <% else %>
      <div class="text-danger far fa-check-square"></div>
      <!--NOT VIEWED
      -->
    <% end %>
    <!--.far.fa-check-square
    -->
    <%= link_to lesson.title, course_lesson_path(@course, lesson) %>
  </div>
  <% if policy(lesson).show? %>
    <div class="card-body">
      <%= lesson.content %>
    </div>
  <% end %>
  <% if policy(lesson).edit? %>
    <div class="card-footer">
      <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' %>
      <%= link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
    </div>
  <% end %>
</div>
<p></p>

app/views/lessons/_lesson_preview.html.erb
<% if lesson.viewed(current_user) == true %>
  <div class="text-success fa fa-check-square"></div>
<% else %>
  <div class="text-danger fa fa-check-square"></div>
<% end %>
<%= link_to lesson.title, course_lesson_path(@course, lesson) %>
<div class="float-right">
  <% if policy(lesson).edit? %>
    <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<%= link_to 'Courses', courses_path %>
\/
<%= link_to @lesson.course.title, course_path(@lesson.course) %>
\/
<%= link_to @lesson.title, course_lesson_path(@course, @lesson) %>
\/
edit lesson
<p></p>



<div class="card">
  <div class="card-header">
    <h3>
    <div class="far fa-check-square"></div>
    Editing lesson
  </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show lesson', course_lesson_path(@course, @lesson) %>
    \|
    <%= link_to 'Back to course', course_path(@lesson.course) %>
  </div>
</div>

app/views/lessons/index.html.erb
<h1>Listing lessons</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Course</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td>
          <%= lesson.title %>
        </td>
        <td>
          <%= lesson.content %>
        </td>
        <td>
          <%= lesson.course %>
        </td>
        <td>
          <%= link_to 'Show', lesson %>
        </td>
        <td>
          <%= link_to 'Edit', edit_lesson_path(lesson) %>
        </td>
        <td>
          <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<%= link_to 'Courses', courses_path %>
\/
<%= link_to @course.title, course_path(@course) %>
\/
new lesson
<p></p>


<div class="card">
  <h3>
    <div class="fa fa-graduation-cap"></div>
    New lesson
  </h3>

  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back to course', course_path(@course) %>
  </div>
</div>

app/views/lessons/show.html.erb
<% content_for :title do %>
  Corsego
  \/
  Course
  <%= @course.title %>
  \/
  Lesson
  <%= @lesson.title %>
<% end %>
<%= link_to 'Courses', courses_path %>
\/
<%= link_to course_path(@lesson.course) do %>
  <div class="fa fa-graduation-cap"></div>
  <%= @lesson.course.title %>
<% end %>
\/
<%= link_to course_lesson_path(@course, @lesson) do %>
  <div class="fa fa-check-square"></div>
  <%= @lesson.title %>
<% end %>
<p></p>
<div class="row">
  <div class="col-lg-8">
    <%= render 'lessons/lesson', lesson: @lesson %>
    <p></p>
  </div>
  <div class="col-lg-4">
    <ul class="list-group">
      <li class="list-group-item">
        <%= link_to course_path(@lesson.course) do %>
          <div class="fa fa-graduation-cap"></div>
          <%= @lesson.course.title %>
        <% end %>
        <div class="row"></div>
        <div class="fa fa-spinner"></div>
        <%= number_to_percentage(@course.progress(current_user), precision: 0) %>
      </li>
      <% @lessons.each do |lesson| %>
        <% if @lesson.present? && lesson == @lesson %>
          <li class="list-group-item list-group-item-success">
            <%= render 'lessons/lesson_preview', lesson: lesson %>
          </li>
        <% else %>
          <li class="list-group-item">
            <%= render 'lessons/lesson_preview', lesson: lesson %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>