config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :lessons
  devise_for :users
  resources :courses do
      get :purchased, :pending_review, :created, :unapproved, on: :collection
      member do
        patch :approve
        patch :unapprove
      end
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  root 'static_pages#landing_page'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'activity', to: 'static_pages#activity'
  resources :users, only: [:index, :edit, :show, :update]
  get 'analytics', to: 'static_pages#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :approve, :unapprove]

  def index
    #if params[:title]
    #  @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    #else
    #  #@courses = Course.all
    #
    #  #@q = Course.ransack(params[:q])
    #  #@courses = @q.result.includes(:user)
    #end

    #if current_user.has_role?(:admin)
    #  @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    #  @courses = @ransack_courses.result.includes(:user)
    #else
    #  redirect_to root_path, alert: 'You do not have access'
    #end

    @ransack_path = courses_path

    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    #@courses = @ransack_courses.result.includes(:user)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))

  end

  def purchased
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def created
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def approve
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course approved and visible!"
  end

  def unapprove
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course upapproved and hidden!"
  end

  def show
    @lessons = @course.lessons
    @enrollments_with_review = @course.enrollments.reviewed
  end

  def new
    @course = Course.new
    authorize @course
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: 'Course has enrollments. Can not be destroyed.'
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price,
        :published, :language, :level)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analytics", course_path(course)
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do
          #"You bought this course. Keep learning" +
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else
        link_to "Free", new_course_enrollment_path(course), class: 'btn btn-success'
      end
      #logic to buy
    else
      link_to "Check price", course_path(course), class: "btn btn-md btn-success"
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-dark fa fa-question'></i>".html_safe + " " +
            'Add a review'
          end
        else
          link_to enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='fa fa-check'></i>".html_safe + " " +
            'Thanks for reviewing! Your Review'
          end
        end
      end
    end
  end

end

app/views/courses/_course.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-graduation-cap"></div>
    <%= link_to course.title, course_path(course) %>
  </div>
  <div class="card-body">
    <small>
      <%= simple_format(course.short_description) %>
    </small>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <%= enrollment_button(course) %>
      <div class="row"></div>
      <%= review_button(course) %>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-md-6">
        <div class="text-warning fa fa-star"></div>
        <b>
          <%= course.average_rating %>
        </b>
        <!--Enrollments count:
        -->
        <!--= course.enrollments.count
        -->
        <!--Counter cache enrollments count:
        -->
        (
        <div class="fa fa-user-graduate"></div>
        <%= course.enrollments_count %>
        )
        <div class="fa fa-tasks"></div>
        <%= course.lessons_count %>
      </div>
      <div class="col-md-6">
        <div class="text-right">
          <div class="fa fa-chalkboard-teacher"></div>
          <%= link_to course.user.username, user_path(course.user) %>
        </div>
      </div>
    </div>
  </div>
  <!--.card-footer
  -->
  <!--  .row
  -->
  <!--    .col-md-6
  -->
  <!--      .fa.fa-globe-africa
  -->
  <!--      = course.language
  -->
  <!--    .col-md-6
  -->
  <!--      .text-right
  -->
  <!--        .fa.fa-signal
  -->
  <!--        = course.level
  -->
  <!--.card-footer
  -->
  <!--  .row
  -->
  <!--    .col-md-6
  -->
  <!--      .far.fa-clock
  -->
  <!--      = course.created_at.strftime('%d-%b-%Y')
  -->
  <!--    .col-md-6
  -->
  <!--      .text-right
  -->
  <!--        .fa.fa-chalkboard-teacher
  -->
  <!--        = link_to course.user.username, user_path(course.user)
  -->
  <% if current_user %>
    <% if policy(course).edit? %>
      <div class="card-footer">
        <% if policy(course).owner? %>
          <%= link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-primary btn-sm' %>
        <% end %>
        <!--- if policy(course).edit?
        -->
        <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' %>
        <!--- if policy(course).destroy?
        -->
        <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
    <% if policy(course).destroy? %>
      <div class="card-footer">
        <% if course.published? %>
          <div class="badge bg-success">published</div>
        <% else %>
          <div class="badge bg-danger">unpublished</div>
        <% end %>
        <% if course.approved? %>
          <div class="badge bg-success">approved</div>
        <% else %>
          <div class="badge bg-danger">unapproved</div>
        <% end %>
      </div>
    <% end %>
    <% if policy(course).approve? %>
      <div class="card-footer">
        <% if course.approved? %>
          <%= link_to 'unapprove', unapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-danger' %>
        <% else %>
          <%= link_to 'approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-success' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/courses/_form.html.erb
<div class="container">
  <% # frozen_string_literal: true %>
  <%= simple_form_for(@course) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :title %>

      <%= f.label :description %>
      <%= f.rich_text_area :description %>

      <%= f.input :short_description %>
      <!--= f.input :language, collection: [ "English", "Polish", "Russian"]
      -->
      <%= f.input :language, collection: Course.languages, include_blank: true %>
      <!--= f.input :level, collection: [ "Beginner", "Intermediate", "Advanced"]
      -->
      <%= f.input :level, collection: Course.levels, include_blank: true %>
      <%= f.input :price %>
      <%= f.input :published %>

    </div>
    <div class="form-actions mt-2">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<% content_for :title do %>
  Corsego
  | Edit
  <%=  @course.title %>
<% end %>


<div class="card">
  <div class="card-header">
    <h3>
    <div class="fa fa-graduation-cap"></div>
      Editing course
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @course %>
    \|
    <%= link_to 'Back', courses_path %>
  </div>
</div>

app/views/courses/index.html.erb
<% content_for :title do %>
  Corsego
  \|
  <%= action_name.humanize %>
  courses
<% end %>
<h3>
  <div class="text-center">
    <div class="fa fa-graduation-cap"></div>
    <%= action_name.humanize %>
    courses
    <div class="badge badge-info text-black">
      <%= @courses.count %>
    </div>
  </div>
</h3>
<p></p>
<div class="row">
  <div class="col-md-2">
    <!--= search_form_for @q do |f|
    -->
    <%= search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f| %>
      <%= f.label :title %>
      <%= f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm' %>
      <%= f.label :description %>
      <%= f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm' %>
      <!--= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm'
      -->
      <!--= f.select :language_cont, ['English', 'Polish', 'Russian'], include_blank: true, class: 'form-control form-control-sm'
      -->
      <%= f.label :language %>
      <%= f.select :language_cont, Course.languages, include_blank: true %>
      <!--= f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-control-sm'
      -->
      <%= f.label :level %>
      <%= f.select :level_cont, Course.levels, include_blank: true %>
      <%= f.label :price %>
      <%= f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm' %>
      <%= f.label :teacher %>
      <%= f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm' %>
      <div class="row"></div>
      <%= sort_link(@ransack_courses, :price) %>
      <div class="row"></div>
      <%= sort_link(@ransack_courses, :average_rating, "Top Rated") %>
      <div class="row"></div>
      <%= sort_link(@ransack_courses, :enrollments_count, "Most Popular") %>
      <div class="row"></div>
      <%= sort_link(@ransack_courses, :created_at, "Fresh") %>
      <div class="row"></div>
      <%= f.submit %>
    <% end %>
    <%= link_to 'refresh', @ransack_path %>
  </div>
  <div class="col-md-10">
      <div class="card-columns d-flex flex-wrap">
        <% @courses.each do |course| %>
          <%= render 'courses/course', course: course %>
        <% end %>
      </div>
    <!--!= pagy_nav(@pagy)
    -->
    <%= raw(pagy_bootstrap_nav(@pagy)) %>
  </div>

</div>
<br/>

app/views/courses/new.html.erb
<% content_for :title do %>
  Corsego
  |
  Add a new course
<% end %>


<div class="card">
  <div class="card-header">
    <h3>
    <div class="fa fa-graduation-cap"></div>
      New course
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', courses_path %>
  </div>
</div>

app/views/courses/show.html.erb
<% content_for :title do %>
  Corsego
  \/
  <%= @course.title %>
<% end %>
<%= link_to 'Courses', courses_path %>
\/
<%= link_to course_path(@course) do %>
  <div class="fa fa-graduation-cap"></div>
  <%= @course.title %>
<% end %>
<div class="row">
  <div class="col-lg-8 order-1 order-lg-1">
    <div class="jumbotron">
      <h3>
        <div class="fa fa-graduation-cap"></div>
        <%= @course.title %>
      </h3>
      <div class="p-3"></div>
      <div class="row"></div>
      <div class="fa fa-clock"></div>
      <%= @course.updated_at.strftime("%m/%Y") %>
      <div class="row"></div>
      <div class="fa fa-globe-africa"></div>
      <%= @course.language %>
      <div class="row"></div>
      <div class="fa fa-signal"></div>
      <%= @course.level %>
      <div class="p-3"></div>
      <%= @course.description %>
    </div>
    <h4>
      <div class="fa fa-tasks"></div>
      <%= pluralize(@course.lessons_count, 'lesson') %>
      <!--Lessons:
      -->
      <!--= @course.lessons_count
      -->
      <div class="float-right">
        <div class="fa fa-spinner"></div>
        <%= number_to_percentage(@course.progress(current_user), precision: 0) %>
      </div>
    </h4>
    <ul class="list-group">
      <% @lessons.each do |lesson| %>
        <li class="list-group-item">
          <%= render 'lessons/lesson_preview', lesson: lesson %>
        </li>
      <% end %>
    </ul>
    <p></p>
    <h4>
      <div class="fa fa-comment"></div>
      <%= pluralize(@enrollments_with_review.count, 'review') %>
      <!--Reviews:
      -->
      <!--= @enrollments_with_review.count
      -->
    </h4>
    <% @enrollments_with_review.each do |enrollment| %>
      <%= render 'enrollments/enrollment', enrollment: enrollment %>
      <p></p>
    <% end %>
  </div>
  <div class="col-lg-4 order-0 order-lg-1">
    <div class="sticky-top">
      <%= render 'courses/course', course: @course %>
    </div>
    <p></p>
  </div>
</div>